name: tuyensinh_ctu
description: A Flutter project providing information of Can Tho University.

dependencies:
  http: "^0.11.3+16"
  html: any
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  html2md: ^0.2.1
  flutter_markdown: ^0.2.0
  url_launcher: ^3.0.3
  path_provider: ^0.4.1
  chewie: ^0.7.0
  video_player: ^0.6.4
  dialogflow: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.1

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/logo_dhct.png"

flutter:

  uses-material-design: true

  assets:
    - assets/logo_dhct.png
    - assets/placeholder.png